---
sidebar: sidebar 
permalink: docs/task_upgrade_element_latest_healthtools.html 
summary: Como parte de una actualización del sistema, debe actualizar al software HealthTools para NetApp Element más reciente. 
keywords: netapp, HealthTools upgrade, sfupdate-healthtools, element 
---
= Actualice a la versión más reciente de HealthTools
:allow-uri-read: 


[role="lead"]
Antes de iniciar la actualización del almacenamiento de Element, debe actualizar la suite HealthTools. Actualizar HealthTools solo es necesario si el nodo de gestión y el software Element que está ejecutando es 11.1 o anterior. HealthTools no es necesario para realizar actualizaciones de elementos mediante el control de cloud híbrido de NetApp.

.Lo que necesitará
* Este sistema ejecuta el nodo de gestión 11.0, 11.1 o posterior.
* Ha actualizado sus servicios de administración a al menos la versión 2.1.326.
+
Las actualizaciones de control de cloud híbrido de NetApp no están disponibles en versiones anteriores del paquete de servicio.

* Ha descargado la versión más reciente de https://mysupport.netapp.com/site/products/all/details/element-healthtools/downloads-tab["HealthTools"^] y copiado el archivo de instalación en el nodo de gestión.
+

TIP: Puede comprobar la versión instalada localmente de HealthTools ejecutando el `sfupdate-healthtools -v` comando.

* Para usar HealthTools con sitios oscuros, debe realizar estos pasos adicionales:
+
** Descargue A link:https://library.netapp.com/ecm/ecm_get_file/ECMLP2840740["Archivo JSON"^] en el sitio de soporte de NetApp en un equipo que no es el nodo de gestión y cambie el nombre a `metadata.json`.
** Deje que el nodo de gestión esté activo y en funcionamiento en el sitio oscuro.




.Acerca de esta tarea
Los comandos del conjunto HealthTools requieren privilegios escalados para ejecutarse. Prefacio comandos con `sudo` o escale el usuario a la Privileges raíz.


NOTE: La versión de HealthTools que utilice podría estar más actualizada que la entrada de muestra y la respuesta que se muestra a continuación.

.Pasos
. Ejecute `sfupdate-healthtools <path to install file>` el comando para instalar el nuevo software HealthTools.
+
Entrada de muestra:

+
[listing]
----
sfupdate-healthtools /tmp/solidfire-healthtools-2020.03.01.09.tgz
----
+
Respuesta de ejemplo:

+
[listing]
----
Checking key signature for file /tmp/solidfirehealthtools-2020.03.01.09/components.tgz
installing command sfupdate-healthtools
Restarting on version 2020.03.01.09
sfupdate-healthtools /sf/bin/sfupdate-healthtools -r 2020.03.01.09
installing command sfupgradecheck
installing command sfinstall
installing command sfresetupgrade
----
. Ejecute `sfupdate-healthtools -v` el comando para verificar que la versión instalada se ha actualizado.
+
Respuesta de ejemplo:

+
[listing]
----
Currently installed version of HealthTools:
2020.03.01.09
----


[discrete]
== Obtenga más información

* https://docs.netapp.com/us-en/vcp/index.html["Plugin de NetApp Element para vCenter Server"^]

