---
sidebar: sidebar 
permalink: docs/task_mnode_remove_assets.html 
summary: Aprenda a eliminar activos de nodo de computación del sistema con la API DE REST. 
keywords: netapp, hci, api, REST, remove, compute, asset 
---
= Quite un activo del nodo de gestión
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si sustituye físicamente un nodo de computación o es necesario quitarlo del clúster NetApp HCI, debe quitar el activo del nodo de computación mediante las API del nodo de gestión.

.Lo que necesitará
* El clúster de almacenamiento ejecuta el software NetApp Element 11.3 o una versión posterior.
* Un nodo de gestión se implementó con la versión 11.3 o posterior.


.Pasos
. Introduzca la dirección IP del nodo de gestión seguido de `/mnode/1/` :
+
[listing]
----
https://<ManagementNodeIP>/mnode/1/
----
. Seleccione *autorizar* o cualquier icono de bloqueo e introduzca las credenciales de administración del clúster para los permisos de uso de las API.
+
.. Introduzca el nombre de usuario y la contraseña del clúster.
.. Seleccione *solicitar cuerpo* en la lista desplegable Tipo si el valor no está seleccionado.
.. Introduzca el ID de cliente como `mnode-client` si el valor no se hubiera rellenado todavía.
.. No introduzca un valor para el secreto de cliente.
.. Seleccione *autorizar* para iniciar una sesión.
.. Cierre la ventana.


. Cierre el cuadro de diálogo *autorizaciones disponibles*.
. Seleccione *GET/assets*.
. Seleccione *probar*.
. Seleccione *Ejecutar*.
. Desplácese hacia abajo en el cuerpo de la respuesta a la sección *Compute*, y copie los `parent` valores y `id` para el nodo de cálculo fallido.
. Seleccione *DELETE/assets/{Asset_id}/Compute-Nodes/{Compute_id}*.
. Seleccione *probar*.
. Introduzca los `parent` valores y `id` copiados en un paso anterior.
. Seleccione *Ejecutar*.

