---
sidebar: sidebar 
permalink: docs/task_nde_configure_credentials.html 
summary: Descubra cómo configurar VMware vSphere durante la implementación de NetApp HCI. 
keywords: netapp, hci, netapp deployment engine, deployment, vsphere 
---
= Configurar las credenciales de NetApp HCI
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Durante la implementación, se define un conjunto de credenciales para utilizar en el entorno de VMware vSphere recién implementado, los recursos de computación y almacenamiento de NetApp HCI y el nodo de gestión. Si va a implementar NetApp HCI en un entorno de vSphere existente, estas credenciales no se aplican a la instancia existente de vCenter Server.

.Acerca de esta tarea
Recuerde los puntos siguientes acerca de las credenciales establecidas en el motor de implementación de NetApp HCI:

* *NetApp Hybrid Cloud Control (HCC) o Element UI*: Para iniciar sesión en NetApp HCC o en la interfaz de usuario de Element una vez realizada correctamente la implementación, utilice el nombre de usuario y la contraseña especificados en este paso de implementación.
* *VMware vCenter*: Para iniciar sesión en vCenter (si se instala como parte de la implementación), utilice el nombre de usuario con el sufijo `@vsphere.local` o la cuenta de usuario integrada `Administrator@vsphere.local` y la contraseña especificada en este paso de implementación.
* *VMware ESXi*: Para iniciar sesión en ESXi en los nodos de cálculo, utilice el nombre de usuario `root` y la misma contraseña especificada en este paso de implementación.


Para interactuar con las instancias de VMware vCenter, el control del cloud híbrido de NetApp utilizará una de las siguientes opciones:

* La cuenta de usuario incorporada `Administrator@vsphere.local` en la instancia de vCenter que se instaló como parte de la puesta en marcha.
* Las credenciales de vCenter que se utilizaron para conectar la puesta en marcha de NetApp HCI a una instancia existente de VMware vCenter Server.


.Pasos
. En la página *credenciales*, introduzca un nombre de usuario en el campo *Nombre de usuario*.
. Introduzca una contraseña en el campo *Contraseña*. La contraseña debe cumplir los criterios de contraseña que aparecen en el cuadro *la contraseña debe contener*.
. Confirme la contraseña en el campo *Volver a introducir contraseña*.
. Seleccione *continuar*.


[discrete]
== Obtenga más información

* link:firmware_driver_versions.html["Versiones de firmware y controlador ESXi compatibles para las versiones de NetApp HCI y firmware para los nodos de almacenamiento NetApp HCI"]
* Para actualizar las credenciales de vCenter y ESXi posteriormente, consulte link:task_hci_credentials_vcenter_esxi.html["Actualice las credenciales de vCenter o ESXi"].

