---
sidebar: sidebar 
permalink: docs/task_nde_join_existing_vsphere.html 
summary: Descubra cómo configurar VMware vSphere durante la implementación de NetApp HCI. 
keywords: netapp, hci, netapp deployment engine, deployment, vsphere 
---
= Únase a una puesta en marcha de VMware vSphere existente
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Configure NetApp HCI para aprovechar la puesta en marcha existente de vSphere proporcionando la información de red de vCenter Server y las credenciales.

.Lo que necesitará
* Si se une a una puesta en marcha existente de vSphere 6.7, asegúrese de que vCenter Server ejecute la versión 6.7 Update 1.
* Si se une a una puesta en marcha existente de vSphere 6.5, asegúrese de que vCenter Server ejecute la versión 6.5 Update 2 o una versión posterior.
* Obtenga los detalles de la red y las credenciales de administrador para la implementación existente de vSphere.


.Acerca de esta tarea
Si se unen varios sistemas de vCenter Server conectados mediante vCenter Linked Mode, NetApp HCI solo reconoce uno de los sistemas de vCenter Server.


NOTE: El uso del plugin de NetApp Element para vCenter Server para gestionar recursos de clústeres desde otras instancias de vCenter Server que utilizan link:https://docs.netapp.com/us-en/vcp/vcp_concept_linkedmode.html["VCenter Linked Mode"^] está limitado únicamente a clústeres de almacenamiento local.

.Pasos
. Seleccione *Unirse y extender una implementación de vSphere existente*.
. Introduzca el nombre de dominio o la dirección IP en el campo *vCenter Server Domain Name or IP address*. Si introduce un nombre de dominio, también debe introducir la dirección IP de un servidor DNS activo en el campo *Dirección IP del servidor DNS* que aparece.
. Introduzca las credenciales de un administrador de vSphere en los campos *User Name y Password*.
. Seleccione *continuar*.


[discrete]
== Obtenga más información

* link:firmware_driver_versions.html["Versiones de firmware y controlador ESXi compatibles para las versiones de NetApp HCI y firmware para los nodos de almacenamiento NetApp HCI"]

