---
sidebar: sidebar 
permalink: docs/task_mnode_api_find_mgmt_svcs_version.html 
summary: Las versiones del sistema operativo del nodo de gestión y de los servicios de gestión que utiliza el nodo de gestión mediante la API DE REST. 
keywords: netapp, hci, management node, management services, version, bundle version, what is 
---
= Verifique el sistema operativo del nodo de gestión y las versiones de servicios
:allow-uri-read: 


[role="lead"]
Puede verificar los números de versión del sistema operativo del nodo de gestión, del paquete de servicios de gestión y de los servicios individuales que se ejecutan en el nodo de gestión mediante la API DE REST en el nodo de gestión.

.Lo que necesitará
* El clúster ejecuta el software NetApp Element 11.3 o una versión posterior.
* Un nodo de gestión se implementó con la versión 11.3 o posterior.


.Opciones
* <<Comandos de la API>>
* <<PASOS PARA LA INTERFAZ DE USUARIO DE LA API DE REST>>




== Comandos de la API

* Obtenga información de la versión acerca del sistema operativo del nodo de gestión, el paquete de servicios de gestión y el servicio API del nodo de gestión (mnode-api) que se ejecutan en el nodo de gestión:
+
[listing]
----
curl -X GET "https://<ManagementNodeIP>/mnode/about" -H  "accept: application/json"
----
* Obtenga información de versión sobre los servicios individuales que se ejecutan en el nodo de gestión:
+
[listing]
----
curl -X GET "https://<ManagementNodeIP>/mnode/services?status=running" -H  "accept: */*" -H  "Authorization: Bearer ${TOKEN}"
----
+

NOTE: Usted puede encontrar el portador `${TOKEN}` utilizado por el comando API cuando usted link:task_mnode_api_get_authorizationtouse.html["autorizar"]. El portador `${TOKEN}` está en la respuesta de rizo.





== PASOS PARA LA INTERFAZ DE USUARIO DE LA API DE REST

. Acceda a la interfaz de usuario de API de REST del servicio. Para ello, introduzca la dirección IP del nodo de gestión seguida `/mnode/` de :
+
[listing]
----
https://<ManagementNodeIP>/mnode/
----
. Debe realizar una de las siguientes acciones:
+
** Obtenga información de la versión acerca del sistema operativo del nodo de gestión, el paquete de servicios de gestión y el servicio API del nodo de gestión (mnode-api) que se ejecutan en el nodo de gestión:
+
... Seleccione *GET /about*.
... Seleccione *probar*.
... Seleccione *Ejecutar*.
+
La versión del paquete de servicios de gestión (`"mnode_bundle_version"`), la versión del sistema operativo del nodo de gestión (`"version"`)(`"os_version"` y la versión de la API del nodo de gestión ) se indican en el cuerpo de la respuesta.



** Obtenga información de versión sobre los servicios individuales que se ejecutan en el nodo de gestión:
+
... Seleccione *GET /Services*.
... Seleccione *probar*.
... Seleccione el estado como *en ejecución*.
... Seleccione *Ejecutar*.
+
Los servicios que se ejecutan en el nodo de gestión se indican en el cuerpo de respuesta.







[discrete]
== Obtenga más información

* https://docs.netapp.com/us-en/vcp/index.html["Plugin de NetApp Element para vCenter Server"^]

